// Compiles the two Tailwind surfaces this DS spans into one static stylesheet
// for cfg.cssEntry. Yappr has no single build that emits component CSS:
//   · src/shared/index.css      — Tailwind v3, config-driven (tailwind.config.js)
//   · YapprLanding/app/globals.css — Tailwind v4, CSS-driven (@theme inline)
// Both declare the SAME token values (see the comment block in index.css), so
// concatenating is coherent rather than conflicting.
//
// Order is load-bearing: the v3 app sheet goes FIRST so that where the two
// generations emit the same utility class (.text-sm et al), the v4 landing
// definition — the larger, brand-critical surface — wins on cascade order.
import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT_DIR = join(ROOT, '.design-sync/compiled');
mkdirSync(OUT_DIR, { recursive: true });

// ── 1. app surface: Tailwind v3 CLI, root tailwind.config.js ──────────────
const appOut = join(OUT_DIR, 'app.css');
execFileSync(
  join(ROOT, 'node_modules/.bin/tailwindcss'),
  ['-i', 'src/shared/index.css', '-o', appOut, '--minify=false'],
  { cwd: ROOT, stdio: ['ignore', 'ignore', 'inherit'] },
);

// ── 2. landing surface: Tailwind v4 via postcss ───────────────────────────
// v4 has no CLI installed here; drive the postcss plugin directly. `from` must
// be the real file path so @import "tailwindcss" and content auto-detection
// resolve against YapprLanding/.
const LANDING = join(ROOT, 'YapprLanding');
const postcss = (await import(join(LANDING, 'node_modules/postcss/lib/postcss.js'))).default
  ?? (await import('postcss')).default;
const tw = (await import(join(LANDING, 'node_modules/@tailwindcss/postcss/dist/index.mjs'))).default;

const src = join(LANDING, 'app/globals.css');
const res = await postcss([tw()]).process(readFileSync(src, 'utf8'), { from: src, to: join(OUT_DIR, 'landing.css') });
writeFileSync(join(OUT_DIR, 'landing.css'), res.css);

// ── 3. merge ──────────────────────────────────────────────────────────────
// The brand faces reach the real site through next/font, which generates the
// --font-* CSS variables at build time inside Next. Outside Next neither the
// faces nor the variables exist, so the shipped CSS referenced five undefined
// vars and every design would have rendered in fallback type. Load the same
// families from Google Fonts (next/font's own source) and define the variables
// the stylesheets already reference. @import must lead the file.
const FONTS =
  '@import url("https://fonts.googleapis.com/css2' +
  '?family=Instrument+Serif:ital@0;1' +
  '&family=Inter:wght@300..700' +
  '&family=JetBrains+Mono:wght@400;500;600' +
  '&family=Lato:wght@300;400;700' +
  '&family=Roboto:wght@300;400;500;700' +
  '&family=Cormorant+Garamond:ital,wght@0,400;0,600;1,400' +
  '&display=swap");\n' +
  ':root{' +
  '--font-instrument-serif:"Instrument Serif";' +
  '--font-inter:"Inter";' +
  '--font-jetbrains-mono:"JetBrains Mono";' +
  '--font-lato:"Lato";' +
  '--font-roboto:"Roboto";' +
  '}';

writeFileSync(
  join(OUT_DIR, 'ds.css'),
  [
    '/* Yappr DS — generated by .design-sync/build-css.mjs. Do not edit. */',
    FONTS,
    '/* ── app surface (Tailwind v3, src/shared/index.css) ── */',
    readFileSync(appOut, 'utf8'),
    '/* ── landing surface (Tailwind v4, YapprLanding/app/globals.css) ── */',
    readFileSync(join(OUT_DIR, 'landing.css'), 'utf8'),
  ].join('\n'),
);
console.error(`  css: ds.css written (${(readFileSync(join(OUT_DIR, 'ds.css'), 'utf8').length / 1024).toFixed(0)}KB)`);
