import { describe, it, expect } from 'vitest'
import { ONBOARDING_CONTEXT_PROMPT, parseOnboardingImport } from './onboarding-import'
import { MAX_FACT_CHARS, normalizeFactText } from '../main/context/facts-format'

describe('the prompt asks for facts that can actually be stored', () => {
  it('asks for under 20 words, not 25', () => {
    // The bug this fixes. The prompt asked for "under 25 words" -- about
    // 153 characters -- while normalizeFactText discards anything over
    // MAX_FACT_CHARS (130). Facts between those two numbers were being
    // generated by the model and then silently dropped on import, and the
    // one prompt users actually paste was the one asking for them.
    expect(ONBOARDING_CONTEXT_PROMPT).toMatch(/UNDER 20 WORDS/)
    expect(ONBOARDING_CONTEXT_PROMPT).not.toMatch(/under 25 words/i)
  })

  it('20 words of English fits inside the cap', () => {
    const twenty = 'Uses TypeScript and Tailwind for every new project and always writes the tests before the implementation'
    expect(twenty.split(' ').length).toBeLessThan(20)
    expect(twenty.length).toBeLessThan(MAX_FACT_CHARS)
    expect(normalizeFactText(twenty)).not.toBeNull()
  })

  it('tells the user a long bullet is a lost bullet', () => {
    // Saying "under 20 words" is a rule; saying what happens if you break
    // it is what makes a model obey one.
    expect(ONBOARDING_CONTEXT_PROMPT).toMatch(/discarded on import/)
  })
})

describe('what the prompt asks for', () => {
  it.each([
    ['work, not personal life', /NOTHING PERSONAL/],
    ['specificity over vibes', /BE SPECIFIC/],
    ['standing rules, not to-dos', /DURABLE ONLY/],
    ['project scope over global', /SCOPE CAREFULLY/],
    ['omission over invention', /DO NOT INVENT/],
    ['the people they work with', /^PEOPLE$/m],
    ['project architecture', /stack, framework and architecture/],
  ])('asks for %s', (_label, re) => {
    expect(ONBOARDING_CONTEXT_PROMPT).toMatch(re)
  })

  it('names the failure mode for a misfiled global fact', () => {
    // The live store had "I prefer the notch color to be blue" filed
    // GLOBAL, which then applied to every unrelated project.
    expect(ONBOARDING_CONTEXT_PROMPT).toMatch(/injected into every other project/)
  })
})

describe('PEOPLE is parsed', () => {
  const paste = [
    'Noan builds Yappr, a Mac dictation app.',
    '',
    'GLOBAL',
    '- Uses TypeScript for every new project.',
    '',
    'PEOPLE',
    '- Jeff is a friend and a prospective investor in Yappr.',
    '',
    'PROJECT: Yappr',
    '- An Electron desktop app styled with Tailwind.',
  ].join('\n')

  it('folds people into global, where they apply everywhere', () => {
    const parsed = parseOnboardingImport(paste)
    expect(parsed.global).toContain('Jeff is a friend and a prospective investor in Yappr.')
  })

  it('does not disturb the other sections', () => {
    const parsed = parseOnboardingImport(paste)
    expect(parsed.global).toContain('Uses TypeScript for every new project.')
    expect(parsed.projects['yappr']).toEqual(['An Electron desktop app styled with Tailwind.'])
    expect(parsed.overview).toBe('Noan builds Yappr, a Mac dictation app.')
  })
})
